name: Update NDFD PM Bar 

on:
  schedule:
    - cron: '30 8,20 * * *'

jobs:
  generate_high_temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xarray==2023.6.0 metpy==1.6.2 matplotlib==3.8.0 numpy==1.26.4 netCDF4==1.5.7 siphon==0.9
      
      - name: Delete old plots if they exist
        run: |
          find plots/temps/ndfd/cities/ -name '*.png' -exec rm {} +
      
      - name: Run ndfd_pm_bar.py
        run: python ndfd_pm_bar.py
      
      - name: Commit and push High Temp changes
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          # Stash any changes including untracked files
          git stash push -u
          # Pull with rebase
          git pull --rebase origin main
          # Pop the stash
          git stash pop
          # Add changes to staging area again
          git add plots/temps/ndfd/cities/*.png
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            # Now commit and push
            git commit -m "Update NDFD PM Bar Plots"
            git push origin main
          fi

